In [1]:
from datetime import date

import pandas as pd
import yaml
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
import holidays
from datetime import date

CONEXION A BASE DE DATOS

In [2]:

#ABRIR ARCHIVO DE CONFIGURACION DE CONEXION A BASES DE DATOS
with open('../configuracion.yml', 'r') as f:
    configuracion = yaml.safe_load(f)
    configuracionBaseDatos= configuracion['ADVENTURE_WORKS_DB']
    configuracionBodegaDatos= configuracion['ADVENTURE_WORKS_DW']

# CREAR LAS URLs DE CONEXION

urlBaseDatos = URL.create(
    "mssql+pyodbc",
    username=configuracionBaseDatos['user'],
    password=str(configuracionBaseDatos['password']),
    host=configuracionBaseDatos['host'],
    port=configuracionBaseDatos['port'],
    database=configuracionBaseDatos['dbname'],
    query={"driver": "ODBC Driver 17 for SQL Server"}
)

urlBodegaDatos = URL.create(
    "mssql+pyodbc",
    username=configuracionBodegaDatos['user'],
    password=str(configuracionBodegaDatos['password']),
    host=configuracionBodegaDatos['host'],
    port=configuracionBodegaDatos['port'],
    database=configuracionBodegaDatos['dbname'],
    query={"driver": "ODBC Driver 17 for SQL Server"}
)



# CREAR EL MOTOR DE SQLALCHEMY
motorBaseDatos = create_engine(urlBaseDatos)
motorBodegaDatos = create_engine(urlBodegaDatos)

CREACION DIMENSION DATE

In [3]:
dimensionDate = pd.DataFrame()
dimensionDate.head()

Empty DataFrame
Columns: []
Index: []

TRANSFORMACION

In [5]:
dimensionDate["DateKey"] = None
dimensionDate["FullDateAlternateKey"] = None
dimensionDate["DayNumberOfWeek"]  = None
dimensionDate["EnglishDayNameOfWeek"] = None
dimensionDate["SpanishDayNameOfWeek"] = None
dimensionDate["FrenchDayNameOfWeek"] = None
dimensionDate["DayNumberOfMonth"] = None
dimensionDate["DayNumberOfYear"] = None
dimensionDate["WeekNumberOfYear"] = None
dimensionDate["EnglishMonthName"] = None
dimensionDate["SpanishMonthName"] = None
dimensionDate["FrenchMonthName"] = None
dimensionDate["MonthNumberOfYear"] = None 
dimensionDate["CalendarQuarter"] = None
dimensionDate["CalendarYear"] = None
dimensionDate["CalendarSemester"] = None
dimensionDate["FiscalQuarter"] = None
dimensionDate["FiscalYear"] = None
dimensionDate["FiscalSemester"] = None

dimensionDate.head()

Empty DataFrame
Columns: [DateKey, FullDateAlternateKey, DayNumberOfWeek, EnglishDayNameOfWeek, SpanishDayNameOfWeek, FrenchDayNameOfWeek, DayNumberOfMonth, DayNumberOfYear, WeekNumberOfYear, EnglishMonthName, SpanishMonthName, FrenchMonthName, MonthNumberOfYear, CalendarQuarter, CalendarYear, CalendarSemester, FiscalQuarter, FiscalYear, FiscalSemester]
Index: []

CARGAR A LA BODEGA

In [6]:
dimensionDate.to_sql('dimensionDate',motorBodegaDatos, if_exists='replace',index=False)

0