In [1]:
from datetime import date

import pandas as pd
import yaml
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

CONEXION A BASE DE DATOS

In [2]:

#ABRIR ARCHIVO DE CONFIGURACION DE CONEXION A BASES DE DATOS
with open('../configuracion.yml', 'r') as f:
    configuracion = yaml.safe_load(f)
    configuracionBaseDatos= configuracion['ADVENTURE_WORKS_DB']
    configuracionBodegaDatos= configuracion['ADVENTURE_WORKS_DW']

# CREAR LAS URLs DE CONEXION

urlBaseDatos = URL.create(
    "mssql+pyodbc",
    username=configuracionBaseDatos['user'],
    password=str(configuracionBaseDatos['password']),
    host=configuracionBaseDatos['host'],
    port=configuracionBaseDatos['port'],
    database=configuracionBaseDatos['dbname'],
    query={"driver": "ODBC Driver 17 for SQL Server"}
)

urlBodegaDatos = URL.create(
    "mssql+pyodbc",
    username=configuracionBodegaDatos['user'],
    password=str(configuracionBodegaDatos['password']),
    host=configuracionBodegaDatos['host'],
    port=configuracionBodegaDatos['port'],
    database=configuracionBodegaDatos['dbname'],
    query={"driver": "ODBC Driver 17 for SQL Server"}
)



# CREAR EL MOTOR DE SQLALCHEMY
motorBaseDatos = create_engine(urlBaseDatos)
motorBodegaDatos = create_engine(urlBodegaDatos)

EXTRACCION

In [ ]:

esquemaProduction = "Production"

dimensionSubProductCategory = pd.read_sql_table("ProductSubcategory", motorBaseDatos, esquemaProduction)
dimensionSubProductCategory

c:\Users\dange.DANGERPC\OneDrive\Escritorio\etl-aventure-works\my_env\Lib\site-packages\pandas\io\sql.py:1737: SAWarning: Did not recognize type 'Name' of column 'Name'
  self.meta.reflect(bind=self.con, only=[table_name], views=True)

,ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate
0,1,1,Mountain Bikes,2d364ade-264a-433c-b092-4fcbf3804e01,2008-04-30
1,2,1,Road Bikes,000310c0-bcc8-42c4-b0c3-45ae611af06b,2008-04-30
2,3,1,Touring Bikes,02c5061d-ecdc-4274-b5f1-e91d76bc3f37,2008-04-30
3,4,2,Handlebars,3ef2c725-7135-4c85-9ae6-ae9a3bdd9283,2008-04-30
4,5,2,Bottom Brackets,a9e54089-8a1e-4cf5-8646-e3801f685934,2008-04-30
5,6,2,Brakes,d43ba4a3-ef0d-426b-90eb-4be4547dd30c,2008-04-30
6,7,2,Chains,e93a7231-f16c-4b0f-8c41-c73fdec62da0,2008-04-30
7,8,2,Cranksets,4f644521-422b-4f19-974a-e3df6102567e,2008-04-30
8,9,2,Derailleurs,1830d70c-aa2a-40c0-a271-5ba86f38f8bf,2008-04-30
9,10,2,Forks,b5f9ba42-b69b-4fdd-b2ec-57fb7b42e3cf,2008-04-30
10,11,2,Headsets,7c782bbe-5a16-495a-aa50-10afe5a84af2,2008-04-30
11,12,2,Mountain Frames,61b21b65-e16a-4be7-9300-4d8e9db861be,2008-04-30
12,13,2,Pedals,6d24ac07-7a84-4849-864a-865a14125bc9,2008-04-30
13,14,2,Road Frames,5515f857-075b-4f9a-87b7-43b4997077b3,2008-04-30
14,15,2,Saddles,049fffa3-9d30-46df-82f7-f20730ec02b3,2008-04-30
15,16,2,Touring Frames,d2e3f1a8-56c4-4f36-b29d-5659fc0d2789,2008-04-30
16,17,2,Wheels,43521287-4b0b-438e-b80e-d82d9ad7c9f0,2008-04-30
17,18,3,Bib-Shorts,67b58d2b-5798-4a90-8c6c-5ddacf057171,2008-04-30
18,19,3,Caps,430dd6a8-a755-4b23-bb05-52520107da5f,2008-04-30
19,20,3,Gloves,92d5657b-0032-4e49-bad5-41a441a70942,2008-04-30
20,21,3,Jerseys,09e91437-ba4f-4b1a-8215-74184fd95db8,2008-04-30
21,22,3,Shorts,1a5ba5b3-03c3-457c-b11e-4fa85ede87da,2008-04-30
22,23,3,Socks,701019c3-09fe-4949-8386-c6ce686474e5,2008-04-30
23,24,3,Tights,5deb3e55-9897-4416-b18a-515e970bc2d1,2008-04-30
24,25,3,Vests,9ad7fe93-5ba0-4736-b578-ff80a2071297,2008-04-30
25,26,4,Bike Racks,4624b5ce-66d6-496b-9201-c053df3556cc,2008-04-30
26,27,4,Bike Stands,43b445c8-b820-424e-a1d5-90d81da0b46f,2008-04-30
27,28,4,Bottles and Cages,9b7dff41-9fa3-4776-8def-2c9a48c8b779,2008-04-30
28,29,4,Cleaners,9ad3bcf0-244d-4ec4-a6a0-fb701351c6a3,2008-04-30
29,30,4,Fenders,1697f8a2-0a08-4883-b7dd-d19117b4e9a7,2008-04-30
30,31,4,Helmets,f5e07a33-c9e0-439c-b5f3-9f25fb65becc,2008-04-30
31,32,4,Hydration Packs,646a8906-fc87-4267-a443-9c6d791e6693,2008-04-30
32,33,4,Lights,954178ba-624f-42db-95f6-ca035f36d130,2008-04-30
33,34,4,Locks,19646983-3fa0-4773-9a0c-f34c49df9bc8,2008-04-30
34,35,4,Panniers,3002a5d5-fec3-464b-bef3-e0f81d35f431,2008-04-30
35,36,4,Pumps,fe4d46f2-c87c-48c5-a4a1-3f55712d80b1,2008-04-30
36,37,4,Tires and Tubes,3c17c9ae-e906-48b4-bdd3-60e28d47dcdf,2008-04-30

TRANSFORMACION

In [6]:


dimensionSubProductCategory.rename(columns={
    'ProductSubcategoryID': 'ProductSubcategoryKey',
    'Name' : 'EnglishProductSubcategoryName',
    'ProductCategoryID' : 'ProductCategoryKey'

}, inplace=True)

dimensionSubProductCategory["ProductSubcategoryAlternateKey"] = dimensionSubProductCategory["ProductSubcategoryKey"]
dimensionSubProductCategory["SpanishProductCategoryName"] = None
dimensionSubProductCategory["FrenchProductCategoryName"] = None


dimensionSubProductCategory.drop(columns=[
    'rowguid',
    'ModifiedDate',
], inplace=True)

dimensionSubProductCategory

,ProductSubcategoryKey,ProductCategoryKey,EnglishProductSubcategoryName,ProductSubcategoryAlternateKey,SpanishProductCategoryName,FrenchProductCategoryName
0,1,1,Mountain Bikes,1,None,None
1,2,1,Road Bikes,2,None,None
2,3,1,Touring Bikes,3,None,None
3,4,2,Handlebars,4,None,None
4,5,2,Bottom Brackets,5,None,None
5,6,2,Brakes,6,None,None
6,7,2,Chains,7,None,None
7,8,2,Cranksets,8,None,None
8,9,2,Derailleurs,9,None,None
9,10,2,Forks,10,None,None
10,11,2,Headsets,11,None,None
11,12,2,Mountain Frames,12,None,None
12,13,2,Pedals,13,None,None
13,14,2,Road Frames,14,None,None
14,15,2,Saddles,15,None,None
15,16,2,Touring Frames,16,None,None
16,17,2,Wheels,17,None,None
17,18,3,Bib-Shorts,18,None,None
18,19,3,Caps,19,None,None
19,20,3,Gloves,20,None,None
20,21,3,Jerseys,21,None,None
21,22,3,Shorts,22,None,None
22,23,3,Socks,23,None,None
23,24,3,Tights,24,None,None
24,25,3,Vests,25,None,None
25,26,4,Bike Racks,26,None,None
26,27,4,Bike Stands,27,None,None
27,28,4,Bottles and Cages,28,None,None
28,29,4,Cleaners,29,None,None
29,30,4,Fenders,30,None,None
30,31,4,Helmets,31,None,None
31,32,4,Hydration Packs,32,None,None
32,33,4,Lights,33,None,None
33,34,4,Locks,34,None,None
34,35,4,Panniers,35,None,None
35,36,4,Pumps,36,None,None
36,37,4,Tires and Tubes,37,None,None

CARGAR A LA BODEGA

In [7]:
dimensionSubProductCategory.to_sql('dimensionProductSubCategory',motorBodegaDatos, if_exists='replace',index=False)

37